# Generated by Django 4.1.13 on 2024-01-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_invoice_details_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
